### install it in application server and configure it by following it.

### Download and Extract node exporter

#wget https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-amd64.tar.gz
#tar -zxvf node_exporter-1.6.0.linux-amd64.tar.gz
#unzip the file and move it to "/opt/node_exporter/"
#sudo mv node_exporter-1.6.0.linux-amd64 /opt/node_exporter/ 

# Then make a service for node Exporter .

#[Unit]
#Description=Node Expoter
#After=network.target

#[Service]
#User=root
#Group=root
#ExecStart=/opt/node_exporter/node_exporter
#Restart=always

#[Install]
#WantedBy=multi-user.target

### Then reload and enable node_exporter.service
#sudo systemctl daemon-reload
#sudo systemctl start node_exporter
#sudo systemctl enable node_exporter


services:
  prometheus:
    image: prom/prometheus:latest
    restart: always
    logging:
      driver: "json-file"
      options:
         max-size: "10m"
         max-file: "3"
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
 
  grafana:
    image: grafana/grafana:latest
    restart: always
    logging:
      driver: "json-file"
      options:
         max-size: "10m"
         max-file: "3"
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
 
  pushgateway:
    image: prom/pushgateway:latest
    restart: always
    logging:
      driver: "json-file"
      options:
         max-size: "10m"
         max-file: "3"
    container_name: pushgateway
    ports:
      - "9091:9091"
 
 
volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local